const SettingsActionTypes = {
	TEMPERATURE_UNIT_TO_F: 'TEMPERATURE_UNIT_TO_F',
	TEMPERATURE_UNIT_TO_C: 'TEMPERATURE_UNIT_TO_C',
	WIND_SPEED_TO_MPH: 'WIND_SPEED_TO_MPH',
	WIND_SPEED_TO_KPH: 'WIND_SPEED_TO_KPH',
	PRESSURE_IN_MB: 'PRESSURE_IN_MB',
	PRESSURE_IN_IN: 'PRESSURE_IN_IN'
};

export default SettingsActionTypes;
